# Generated by Django 5.1.4 on 2025-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transactions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='public_key',
            field=models.TextField(default='test', verbose_name='PublicKey'),
        ),
    ]
