# Generated by Django 5.1.4 on 2025-05-30 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accounts_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='RecurringPaymentID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('message', models.TextField(verbose_name='Message')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10, verbose_name='Frequency')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('next_payment_date', models.DateTimeField(verbose_name='Next Payment Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('total_payments_made', models.IntegerField(default=0, verbose_name='Total Payments Made')),
                ('max_payments', models.IntegerField(blank=True, null=True, verbose_name='Maximum Payments')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Payment Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_credits', to='main.accounts')),
                ('withdraw_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_withdrawals', to='main.accounts')),
            ],
            options={
                'verbose_name': 'Recurring Payment',
                'verbose_name_plural': 'Recurring Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
