# Generated by Django 5.1.4 on 2025-06-03 19:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recurringpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('TRANSFER', 'Transfer'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('AUTHORIZE', 'Authorize'), ('REJECT', 'Reject')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('ACCOUNT', 'Account Management'), ('TRANSACTION', 'Transaction'), ('RECURRING', 'Recurring Payment'), ('USER', 'User Management'), ('SECURITY', 'Security Event'), ('SYSTEM', 'System Event')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'category'], name='main_auditl_timesta_b7d980_idx'), models.Index(fields=['user', 'timestamp'], name='main_auditl_user_id_1cd3b6_idx'), models.Index(fields=['severity', 'timestamp'], name='main_auditl_severit_6e25b6_idx'), models.Index(fields=['success', 'timestamp'], name='main_auditl_success_66892e_idx')],
            },
        ),
    ]
