# Generated by Django 5.1.4 on 2025-06-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Backup Codes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_totp_used',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Last TOTP Used'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA Enabled'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_enabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2FA Enabled At'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='2FA Secret'),
        ),
    ]
