# Generated by Django 5.1.4 on 2025-06-04 06:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_backup_codes_profile_last_totp_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='API Key Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('key_hash', models.CharField(max_length=128, unique=True, verbose_name='Key Hash')),
                ('prefix', models.CharField(max_length=8, verbose_name='Key Prefix')),
                ('permissions', models.CharField(choices=[('READ', 'Read Only'), ('READ_WRITE', 'Read and Write'), ('ADMIN', 'Administrative Access')], default='READ_only', max_length=10, verbose_name='Permissions')),
                ('allowed_ips', models.JSONField(blank=True, default=list, verbose_name='Allowed IP Addresses')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('rate_limit', models.IntegerField(default=1000, verbose_name='Rate Limit Per Hour')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='Access Scopes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('request_size', models.IntegerField(blank=True, null=True)),
                ('response_size', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='main.apikey')),
            ],
            options={
                'verbose_name': 'API Key Usage',
                'verbose_name_plural': 'API Key Usage Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_hash'], name='main_apikey_key_has_56e3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['created_by', 'status'], name='main_apikey_created_de8f80_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['status', 'expires_at'], name='main_apikey_status_14f497_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusage',
            index=models.Index(fields=['api_key', 'timestamp'], name='main_apikey_api_key_704ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusage',
            index=models.Index(fields=['timestamp'], name='main_apikey_timesta_99ddff_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusage',
            index=models.Index(fields=['ip_address', 'timestamp'], name='main_apikey_ip_addr_459067_idx'),
        ),
    ]
