# Generated by Django 5.1.4 on 2025-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_apikey_apikeyusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_factor_disabled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2FA Disabled Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_enabled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2FA Enabled Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_setup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2FA Setup Date'),
        ),
    ]
